QT.gui_private.VERSION = 5.10.0
QT.gui_private.name = QtGui
QT.gui_private.module =
QT.gui_private.libs = $$QT_MODULE_LIB_BASE
QT.gui_private.includes = $$QT_MODULE_INCLUDE_BASE/QtGui/5.10.0 $$QT_MODULE_INCLUDE_BASE/QtGui/5.10.0/QtGui
QT.gui_private.frameworks =
QT.gui_private.depends = core_private gui
QT.gui_private.uses =
QT.gui_private.module_config = v2 internal_module
QT.gui_private.enabled_features = xcb egl eglfs eglfs_brcm evdev freetype system-freetype fontconfig gif harfbuzz ico jpeg kms linuxfb multiprocess png system-jpeg system-png vnc xcb-glx xlib xcb-xlib xcb-native-painting xcb-render xinput2 xkb xkbcommon-evdev xrender
QT.gui_private.disabled_features = accessibility-atspi-bridge angle_d3d11_qdtd direct2d directfb egl_x11 eglfs_egldevice eglfs_gbm eglfs_mali eglfs_viv eglfs_viv_wl integrityfb integrityhid libinput libinput-axis-api mirclient mtdev system-harfbuzz system-xcb tslib xcb-sm xkbcommon-system
QMAKE_LIBS_XCB = -lxcb
QMAKE_LIBS_OPENGL_ES2 = -L/Users/jonathancastillo/projects/rpi/sysroot/usr/lib/arm-linux-gnueabihf -lGLESv2
QMAKE_INCDIR_OPENGL_ES2 = =/opt/vc/include =/opt/vc/include/interface/vcos/pthreads =/opt/vc/include/interface/vmcs_host/linux
QMAKE_LIBS_XCB_XLIB = -lxcb -lX11 -lX11-xcb
QMAKE_LIBS_FREETYPE = -L/Users/jonathancastillo/projects/rpi/sysroot/usr/lib/arm-linux-gnueabihf -lfreetype
QMAKE_INCDIR_FREETYPE = /Users/jonathancastillo/projects/rpi/sysroot/usr/include/freetype2
QMAKE_LIBS_FONTCONFIG = -L/Users/jonathancastillo/projects/rpi/sysroot/usr/lib/arm-linux-gnueabihf -lfontconfig -lfreetype
QMAKE_INCDIR_FONTCONFIG = /Users/jonathancastillo/projects/rpi/sysroot/usr/include/freetype2
QMAKE_LIBS_DRM = -L/Users/jonathancastillo/projects/rpi/sysroot/usr/lib/arm-linux-gnueabihf -ldrm
QMAKE_INCDIR_DRM = /Users/jonathancastillo/projects/rpi/sysroot/usr/include/libdrm
QMAKE_LIBS_OPENVG = -L/Users/jonathancastillo/projects/rpi/sysroot/opt/vc/lib -lOpenVG -lbcm_host -lvcos -lvchiq_arm
QMAKE_DEFINES_OPENVG = USE_VCHIQ_ARM
QMAKE_INCDIR_OPENVG = /Users/jonathancastillo/projects/rpi/sysroot/opt/vc/include /Users/jonathancastillo/projects/rpi/sysroot/opt/vc/include/interface/vmcs_host/linux /Users/jonathancastillo/projects/rpi/sysroot/opt/vc/include/interface/vcos/pthreads
QMAKE_LIBS_LIBJPEG = -ljpeg
QMAKE_LIBS_LIBPNG = -L/Users/jonathancastillo/projects/rpi/sysroot/usr/lib/arm-linux-gnueabihf -lpng16
QMAKE_INCDIR_LIBPNG = /Users/jonathancastillo/projects/rpi/sysroot/usr/include/libpng16
QMAKE_LIBS_XCB_GLX = -lxcb-glx -lxcb
QMAKE_LIBS_XRENDER = -lXrender
QMAKE_LIBS_XINPUT2 = -lXi
QMAKE_LIBS_XKBCOMMON_EVDEV = -L/Users/jonathancastillo/projects/rpi/sysroot/usr/lib/arm-linux-gnueabihf -lxkbcommon
